### ISSUE TITLE
Yêu cầu - Hiển thị tên cls phụ lên danh sách.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#1]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87115`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Lao Phôi ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dbphoidt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu chổ danh cách XN được chỉ định hiển thi thêm tên CLS phụ như module hiện tại.

Diagnose
![image](https://user-images.githubusercontent.com/99630883/185857873-dc2d1bac-482c-43e5-947f-b456b88e5cde.png)

Labo hiện tại không hiển thị, yêu cầu hiển thị giống như Diag.
![image](https://user-images.githubusercontent.com/99630883/185859938-5ccc9016-21fa-4c54-a9ac-bdfe67f9e9f0.png)

**Comment by nvvinh-dh** [comment]
Mục đích để làm gì?

**Comment by lqbinh1987** [comment]
Vì có những XN chỉ 1 mã CLS thôi thực hiện bằng nhiều phương pháp, có XN thực hiện tới 4 phương pháp.

Ví dụ: Xét nghiệm AFP trực tiếp nhuộm Ziehl-Neelsen sẽ có 4 phương pháp trả kết quả như (Đàm mẫu 1, Đàm mẫu 2, Dịch, Phân).
Trường hợp cấp cứu hoặc nội trú cần làm gấp thì đẩy BN đi trước không có đem theo phiếu chỉ định, lúc này Khoa XN không biết thực hiện theo phương pháp nào?

**Comment by nvvinh-dh** [comment]
tenclsphu hiện tại chỗ danh sách XN có tên cột riêng. BV Lao ĐT cần thì anh mở cho xài riêng, chứ không có ghép vô tên XN được.
