### ISSUE TITLE
Lỗi - Tách Phiếu kết quả Xét nghiệm Huyết Học !

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#10]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87115`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Phổi Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphoidt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021000636` - _**MaKB**_: `2210001368` - _**MaBA**_: `MaBA` _**NgayKCB**_: `20/10/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `10` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Phiếu huyết học không cấu hình mẫu chuẩn khi in ra cùng kho Huyết học lại tách ra 2 tờ á anh Vinh !
![image](https://user-images.githubusercontent.com/97272364/197125389-58e78003-83ff-4e49-b44b-717b444bf421.png)
Kết quả khi in ra 
![image](https://user-images.githubusercontent.com/97272364/197126077-ba678db2-d83e-4eab-9d88-112f4819983f.png)

![image](https://user-images.githubusercontent.com/97272364/197125545-04636bc8-454e-4e4b-99b4-59fcdb52b641.png)
![image](https://user-images.githubusercontent.com/97272364/197125670-4264006b-f04c-4371-9649-896b225ec3f0.png)

```

**Comment by vinh-dh** [comment]
À, theo mô tả này thì đó là ý đồ đó @hvtuan1987 :[Vinh - Mo ta phieu xet nghiem khi mau [BV Lao Phoi Dong Thap] - 21-04-2022 - v2.pdf](https://github.com/dh-hos/dhg.hospitallaboratory/files/9836269/Vinh.-.Mo.ta.phieu.xet.nghiem.khi.mau.BV.Lao.Phoi.Dong.Thap.-.21-04-2022.-.v2.pdf)

Các xét nghiệm có cấu hình khimau = 2 sẽ tách ra mẫu riêng: 
![image](https://user-images.githubusercontent.com/112069710/197129172-00c35123-159c-4e19-97d7-3e54a11e129e.png)

Do đó, nếu các xét nghiệm con của các XN đã cấu hình khimau = 2 thì có thể nó cũng là XN khí máu luôn. Em xác nhận với BV, nếu đúng như vậy thì các XN con đó em cho cấu hình khimau = 2 luôn thì nó sẽ lên chung 1 mẫu.

**Comment by hvtuan1987** [comment]
ok anh !

Vào Th 6, 21 thg 10, 2022 vào lúc 13:40 vinh-dh ***@***.***>
đã viết:
