### ISSUE TITLE
Lỗi - Sổ xét nghiệm không có tên người đọc kết quả

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#12]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_bs_kqxn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022003556` - _**MaKB**_: `2209001249` - _**MaBA**_: `2022007319` _**NgayKCB**_: `05/09/2022` -  _**MaDV**_: `CC` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Sổ xét nghiệm không hiển thị tên người đọc kết quả xét nghiệm!

```
Sổ xét nghiệm
![image](https://user-images.githubusercontent.com/96155021/197716955-c4b89287-9c42-48df-afcc-c0d2e3c8f1d3.png)
Sổ xét nghiệm tt14 có tên người đọc
![image](https://user-images.githubusercontent.com/96155021/197717086-28b77e67-0893-4789-8431-e16f99882051.png)
Form trả kết quả
![image](https://user-images.githubusercontent.com/96155021/197717196-7569a730-af6f-43c2-8aa5-fe15db6dc800.png)
Tài khoản trả kết quả
![image](https://user-images.githubusercontent.com/96155021/197717301-5c509d6c-65a4-4ba8-8551-8de20384b6db.png)

**Comment by vinh-dh** [comment]
Do BV sử dụng tham số xn.bacsixn = 0
![image](https://user-images.githubusercontent.com/112069710/197721227-c143f2b6-effd-4f4c-ab4a-4d79aaf3aaa9.png)

Tham số xn.truongkhoa đang rỗng
![image](https://user-images.githubusercontent.com/112069710/197721400-770f7c42-753f-4643-824c-8d912eb4b7fa.png)

Để a fix Sổ XN 14 cho khớp với Sổ XN thường luôn.

**Comment by le-an-87** [comment]
ok anh!

**Comment by vinh-dh** [comment]
Bản này [Laboratory 26/10/2022](https://www.fshare.vn/file/VL15BV8985TC) anh fix sổ XN 14 cho khớp với sổ XN thường luôn nhé @le-an-87.
