### ISSUE TITLE
Yêu cầu - Hỗ trợ mẫu sổ 15/BV-01  SỔ XÉT NGHIỆM TẾ BÀO MÁU NGOẠI VI

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#13]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87144`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quân Dân Y Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_qdydt_socdha`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh viện nhờ hỗ trợ mẫu sổ Xét nghiệm TẾ BÀO MÁU NGOẠI VI MS: 15/BV-01 để hỗ trợ việc thanh quyết toán BHYT
Mẫu sổ như hình dưới 
![image](https://user-images.githubusercontent.com/97272364/197925695-34a837ab-82bc-40fa-910d-51f163da13b0.png)
![image](https://user-images.githubusercontent.com/97272364/197925766-c7010845-f318-4400-9662-b69bb2c5889e.png)

```

**Comment by vinh-dh** [comment]
Phần này theo hợp đồng bảo trì là không có. Thêm nữa là mẫu này nhiều thông tin phần mềm chưa có quản lý. Nếu làm thì báo giá để làm đi @nghivanbi. Còn không thì đợi nghiên cứu.

**Comment by nghivanbi** [comment]
Thực hiện sổ Xét nghiệm TẾ BÀO MÁU NGOẠI VI MS: 15/BV-01 nha, thông tin nào có đưa lên.

**Comment by vinh-dh** [comment]
Local:
- [HospitalLaboratorySetup20230106](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20230106.zip)
- [SetupHospitalReport20230106](http://192.168.10.79:8090/Reports/SetupHospitalReport20230106.zip)

Fshare:
- [HospitalLaboratorySetup20230106](https://www.fshare.vn/file/GQ4ZFVS5Y8XS)
- [SetupHospitalReport20230106](https://www.fshare.vn/file/KF8KWLZU3MIH)

**Comment by nghivanbi** [comment]
@hvtuan1987 check lại nha
