### ISSUE TITLE
Yêu cầu - Hỗ trợ mẫu  SỔ XÉT NGHIỆM VI SINH 18/BV-01

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#14]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87144`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quân Dân Y Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_qdydt_socdha`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh viện nhờ hỗ trợ mẫu SỔ XÉT NGHIỆM VI SINH 18/BV-01 để hỗ trợ việc thanh quyết toán BHYT
Mẫu sổ như hình dưới 
![image](https://user-images.githubusercontent.com/97272364/197926521-1660d807-acbb-43f2-93fc-f19cce4c9baa.png)
![image](https://user-images.githubusercontent.com/97272364/197926569-f4b59959-1caa-4a43-99e6-7c57a8083861.png)

```

**Comment by vinh-dh** [comment]
Mẫu này cũng tương tự như #13

**Comment by nghivanbi** [comment]
Hỗ trợ mẫu Sổ xét nghiệm vi sinh nha, thông tin nào có thì đưa lên sổ.

**Comment by vinh-dh** [comment]
Cái chỗ yêu cầu này anh thấy có thể làm cái chỗ cho người dùng tự cấu hình (tức là tự đưa mã XN của vi sinh tương ứng vào đó được):
![image](https://user-images.githubusercontent.com/112069710/201825677-86ebfba2-68e5-40ac-9cb0-cb9d7c55f8f4.png)

Nhưng cái kháng sinh đồ này:
![image](https://user-images.githubusercontent.com/112069710/201825727-2206010a-6a2f-4b94-abbb-ee684c5820a6.png)

Thì nó tương ứng như thế nào với cái kết quả vậy?
![image](https://user-images.githubusercontent.com/112069710/201825757-188821cc-4213-4202-a97d-70356598188b.png)

Em hỏi chi tiết BV đi @hvtuan1987

**Comment by hvtuan1987** [comment]
Em hỏi Bv nhưng BV cũng hong rành lắm, theo em anh để BV tự cấu hình là ok
nhất ! Hoặc anh theo thứ tự từ trên xuống theo mẫu kháng sinh đồ đó luôn á
anh Vinh !
Em thấy nó có 30 loại chủng kháng tương ứng với 30 cột trên mẫu á !

Vào Th 3, 15 thg 11, 2022 vào lúc 11:23 vinh-dh ***@***.***>
đã viết:

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20221123](https://www.fshare.vn/file/G7F8L148KS1J)
- [HospitalLaboratorySetup20221123](https://www.fshare.vn/file/IOMRSD5D7L6Q)

**Comment by hvtuan1987** [comment]
ok anh !
