### ISSUE TITLE
Yêu cầu - CLS có Cls con không cho bỏ check CLS con khi lấy mẫu

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitallaboratory#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_thanhtri`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Khi chỉ định CLS có Cls con thì Labo không cho BỎ CHECK TH Cls con khi LẤY MẪU. Nếu bỏ check thì bỏ check CLS cha 

```
![image](https://user-images.githubusercontent.com/98437757/203210534-8fcbb17b-3203-4e5e-a303-b1b4d1675925.png)

**Comment by vinh-dh** [comment]
Trường hợp này là nhu cầu của BV. Bỏ là rất nhiều BV sẽ không đồng ý. Còn chỉ có 1 trường hợp duy nhất của Thạnh Trị do sơ suất thì nói khoa XN kỹ chỗ lấy mẫu (vì mặc định đã check toàn bộ khi lấy mẫu)
