### ISSUE TITLE
Lỗi - Báo cáo lượt thực hiện xét nghiệm chi tiết

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ct_full_14112022`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   >**NgayKCB**_: `06/11/2022` - _**ThangKT**_: `11` - _**NamKT**_: `2022`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `I01`
   > _**MaCLS**_: `DI54`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Anh Vinh ơi kiểm tra giùm em báo cáo Lượt thực hiện xét nghiệm chi tiết
- Mã cls: I01 có số lượng Mẫu nhiều hơn số lượt.
- Mã cls: DI54 không có số lượng mẫu.

```
![image](https://user-images.githubusercontent.com/96155021/205192989-08152905-428d-4766-9e02-7ab8824dc405.png)

**Comment by vinh-dh** [comment]
À, do BV cấu hình mẫu xét nghiệm như vầy, nên số liệu thống kê nó ra như vậy đó.

![image](https://user-images.githubusercontent.com/112069710/205196495-ec217a98-ae90-4975-b4a5-4bf3aced4d6e.png)

![image](https://user-images.githubusercontent.com/112069710/205196514-5e570303-6e32-43b4-8db5-dda2ef4276d3.png)

**Comment by le-an-87** [comment]
ok anh!
