### ISSUE TITLE
Yêu cầu - Ghi nhận nhân viên lấy mẫu vào phiếu chỉ định nồng độ cồn.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#2]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_malk__`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại trên phiếu **Kết quả xét nghiệm nồng đọ cồn trong máu** có mục **Người lấy mẫu(Họ và tên):**, phần mềm đáp ứng được theo hướng đăng nhập tk nhân viên lấy mẫu rồi chọn nhân viên thực hiện, nhưng trường hợp người lấy mẫu là công an, không phải nhân viên của BV, thì không ghi nhận được.
Đề nghị form trả kết quả có Check để thể hiện textbox cho phép nhập tên nhân viên lấy mẫu vào:
 - Nếu không Check thì lấy mặc định tk đăng nhập.
 - Nếu có Check thì lấy giá trị nhập vào ô textbox, đồng thời lưu giá trị này vào CSDL để lần sau có in lại thì in.
 
![image](https://user-images.githubusercontent.com/99630883/188591420-a7a28637-2ccc-42d1-a982-2ddcf4c9f9a7.png)

**Comment by vinh-dh** [comment]
Xác định yêu cầu kỹ nhe @lqbinh1987. Trong khi phiếu yêu cầu có thông tin xác định mẫu lấy:
![image](https://user-images.githubusercontent.com/112069710/188596812-9f44ef41-03b0-4506-976d-d2068c639585.png)

Như vậy là việc xác định mẫu (bao gồm người lấy mẫu) ở khâu bác sĩ lâm sàng chứ không phải ở khâu nhập kết quả đâu nhe! Xác nhận lại đi!
