### ISSUE TITLE
Yêu cầu - Bổ sung một số trường vào mẫu trả Kq Xét nghiệm nồng độ cồn

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitallaboratory#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Giá Rai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_giarai_labo`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bổ sung thêm thông tin: Tuổi, Giới tính, Địa chỉ, Khoa, Buồng, Giường, Chẩn đoán vào mẫu Trả KQ Phiếu Xét nghiệm nồng độ cồn trong máu theo TTLT số 26/2014/TTLT-BYT-BCA
Trung tâm y tế Giá Rai gởi kèm theo đề nghị

```
[BDN.pdf](https://github.com/dh-hos/dhg.hospitallaboratory/files/10242589/BDN.pdf)

**Comment by vinh-dh** [comment]
@nghivanbi báo giá BV nhé!

**Comment by nghivanbi** [comment]
Thực hiện yêu cầu nha.

**Comment by vinh-dh** [comment]
> Thực hiện yêu cầu nha. [Mauxacnhan.pdf](https://github.com/dh-hos/dhg.hospitallaboratory/files/10639473/Mauxacnhan.pdf)

@nghivanbi hiểu cái y/c của BV không? [Mauxacnhan.pdf](https://github.com/dh-hos/dhg.hospitallaboratory/files/10639473/Mauxacnhan.pdf) này thì phần mềm đang làm theo nó rồi đó!

**Comment by nghivanbi** [comment]
+ Thực hiện như sau:
- Chuyển phiếu kết quả mẫu 03 hiện tại sang XtraReport (làm mẫu mặc định)
- Bổ sung các parameter theo yêu cầu  (để hướng dẫn bệnh viện tự bổ sung lên phiếu khi có nhu cầu)
Phạm vị: tất cả khách hàng.

**Comment by vinh-dh** [comment]
Local:
- [HospitalLaboratorySetup20230210](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20230210.zip)

Fshare:
- [HospitalLaboratorySetup20230210](https://www.fshare.vn/file/IBQHWU8CQEGU)

**Comment by le-an-87** [comment]
đã bổ sung mẫu tự thiết kế!
