### ISSUE TITLE
Lỗi - không vào được chức năng phân quyền

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#24]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Giá Rai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) ``
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`[Tải về tại đây](https://drive.google.com/file/d/1M5J9xjG2q0W4i-1WYpEexuho5bkZzCcv/view?usp=share_link)`](link_csdl)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng phân quyền bị ẩn không vào được!
link dữ liệu: https://drive.google.com/file/d/1M5J9xjG2q0W4i-1WYpEexuho5bkZzCcv/view?usp=share_link
```
![image](https://user-images.githubusercontent.com/96155021/213371278-cb2be629-77ac-41e9-85de-1b31f213b5b0.png)

**Comment by vinh-dh** [comment]
Vẫn còn nhe @le-an-87 
![image](https://user-images.githubusercontent.com/112069710/213612531-ca1e9dbe-ce94-4649-b135-98b9a4982ca8.png)

Nói bệnh viện chỉnh độ phân giải cao lên, do độ phân giải thấp nó bị khuất bên dưới

**Comment by vinh-dh** [comment]
Bổ sung phím tắt [F6] để ẩn/hiện cụm gọi số.

Local:
- [HospitalLaboratorySetup20230130](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20230130.zip)

Fshare:
- [HospitalLaboratorySetup20230130](https://www.fshare.vn/file/LN5HR4W28NCJ)

**Comment by le-an-87** [comment]
đã bổ sung!
