### ISSUE TITLE
Yêu cầu - Phiếu kết quả nồng độ cồn bổ sung thêm các parametter theo mẫu kèm theo (khoa chỉ đinh, buồng, giường)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#25]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Giá Rai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_giarai_laboratory_phanquyen`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000001` - _**MaKB**_: `2301009462` - _**NgayKCB**_: `10/02/2023` - _**MaPhong**_: `28` - _**MaDV**_: `10` - _**ThangKT**_: `02` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Phiếu kết quả nồng độ cồn bổ sung thêm các parametter theo mẫu kèm theo
-> còn thiếu trường: khoa chỉ đinh, buồng, giường
```
Đề nghị bv
![image](https://user-images.githubusercontent.com/96155021/218624561-fcbba32c-acce-43ca-b3cb-811dc35d32ce.png)

Mẫu kèm theo của bệnh viện thiếu Trường *Khoa, Buồng, Giường*
![image](https://user-images.githubusercontent.com/96155021/218626610-85fd7eb9-f480-475a-9ee3-5065118dfbe7.png)

Mẫu thiết kế
![image](https://user-images.githubusercontent.com/96155021/218624741-e2181533-1194-4f06-9d99-eda1f3c1f9af.png)

**Comment by vinh-dh** [comment]
Khoa chỉ định là _18_tendv đó @le-an-87. Còn buồng và giường sao đợt y/c BV không đưa 1 lượt luôn.

**Comment by le-an-87** [comment]
mẫu đó là mẫu nó gửi kèm theo đó anh! trong yêu cầu nó không có để nhưng trong mẫu thì có

**Comment by vinh-dh** [comment]
Anh chỉ quan tâm tới phần y/c, nên ko để ý cái mẫu đó. Để anh thêm para buồng và giường.

**Comment by vinh-dh** [comment]
Local:
- [HospitalLaboratorySetup20230215](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20230215.zip)

Fshare:
- [HospitalLaboratorySetup20230215](https://www.fshare.vn/file/QX97WOGX4EFO)

**Comment by le-an-87** [comment]
đã bổ sung!
