### ISSUE TITLE
Lỗi - Kết quả xét nghiệm Đòm sau khi lưu kết quả vào lại bị mất

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#26]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trung tâm y tế huyện Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023002462` - _**MaKB**_: `2302004152` - _**MaBA**_: `MaBA` _**NgayKCB**_: `24/02/2023` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Bệnh nhân coa kết quả xét nghiệm đòm sau khi gõ kết quả Bấm nút Lưu và hiển thị phiếu kết quả. Nhưng sau đó bấm vô lại thì kết quả bị mất !

![image](https://user-images.githubusercontent.com/97272364/221114582-e39530ed-bb17-4b59-9ed0-182c21938a4d.png)
Sau đó vào lại thì hiển thị như hình dưới()
![image](https://user-images.githubusercontent.com/97272364/221114674-08bdfa87-a804-49cd-a7dd-9760c0ac2121.png)

```

**Comment by vinh-dh** [comment]
Local:
- [HospitalLaboratorySetup20230224](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20230224.zip)

Fshare:
- [HospitalLaboratorySetup20230224](https://www.fshare.vn/file/YTXXLYPEJBMW)

**Comment by hvtuan1987** [comment]
ok rồi á anh !
