### ISSUE TITLE
Yêu cầu - Nội dung nhật ký nhầm thông tin.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_st_2023_02_10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2017013153` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023001025` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN điều trị nội trú chỉ định cls, trả kết quả xong -> hủy kết quả, thì nhật ký ghi nhận cột nội dung hiển thị mã khám bệnh của ngoại trú chứ không phải mã bệnh án nội trú, còn trên form danh sách bệnh nhân thì lại hiển thị phù hợp mã bệnh án nội trú vì là bn điều trị nội trú -> dẫn đến khó kiểm soát cũng như kiểm tra.
=> Đề nghị khi ghi nhận nhật ký theo cấu trúc  thì bổ sung thêm Mã BN ở phía đầu, đồng thời kèm thêm:
-  Mã khám bệnh nếu là ngoại trú .
- Mã bệnh án nếu là nội trú hoặc BANT theo đợt.
Ví dụ: BN nội trú [2012999999][**2023**000001]...nội dung.....
          BN ngoại trú [2012999999][**2302**000001]...nội dung.....

![image](https://user-images.githubusercontent.com/99630883/222057982-0b8e9430-fd55-4207-a3ff-978fad3e97a5.png)
![image](https://user-images.githubusercontent.com/99630883/222058236-08a67f44-31d6-47e1-9a3d-bb20d59f0413.png)

**Comment by vinh-dh** [comment]
Nếu vậy em đổi topic lại là y/c mới đúng nhe. Vì đây không phải lỗi phần mềm.
