### ISSUE TITLE
Yêu cầu - Ghi nhận dữ liệu bị hủy.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#28]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_st_2023_02_10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Khi hủy kết quả thì hiện tại phần mềm đang thực hiện delete trong dữ liệu luôn, cụ thể là pskhamxn và psmotaxn.
Đề nghị khi hủy kết quả thì đánh dấu xóa trong dữ liệu, để tiện cho việc khi có trường hợp lỗi phần mềm, đã trả kết quả rồi, **có in phiếu KQ rồi luôn**, nhưng phần mềm lại mất kết quả, kiểm tra thì ko thấy nhật ký hủy => **KHÔNG có cơ sở để đối chiếu**

**Comment by vinh-dh** [comment]
Hiện tại dữ liệu 2 table đó là rất lớn. Hủy không xóa thì ảnh hưởng tới tốc độ truy cập sau này. Thêm nữa là đã có ghi nhật ký thao tác hủy rồi. Nếu đã hủy mà không có nhật ký thì là lỗi phần mềm. Các trường hợp đó đề nghị test lỗi để fix luôn.

**Comment by lqbinh1987** [comment]
ok anh, để e ghi nhận
