### ISSUE TITLE
Lỗi - Xét nghiệm có trả kết quả nhưng in phiếu kết quả không có

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#3]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phước Long BL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phuoclong_kqxn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000424` - _**MaKB**_: `2209004806` - _**NgayKCB**_: `13/09/2022` - _**MaCLS**_: `TH228` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xét nghiệm TH228 có trả kết quả nhưng in phiếu kết quả xét nghiệm không có cls này

```
Trả kết quả TH228
![image](https://user-images.githubusercontent.com/96155021/190037654-89334b3c-8ca6-416f-bc08-c3c7477d1dd5.png)

![image](https://user-images.githubusercontent.com/96155021/190037551-b1609c06-1ed9-450b-8fa1-41d822798558.png)
Phiếu kết quả huyết học không có cls TH228
![image](https://user-images.githubusercontent.com/96155021/190037612-7d043edc-6296-4236-8bb0-ed7694406609.png)

**Comment by vinh-dh** [comment]
Đã fix [Laboratory 14/09/2022](https://www.fshare.vn/file/T4TJWNCH3Q6E)
