### ISSUE TITLE
Yêu cầu - Bổ sung hàm API lấy mẫu theo CLS.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#30]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87014 `
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Sa Đéc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu bổ sung thêm hàm api lấy mẫu từng CLS như chức năng chọn CLS lấy mẫu ở Laboratory

**Comment by vinh-dh** [comment]
Anh đã update API cho Sa Đéc rồi nhé @lqbinh1987. Em gửi tài liệu này: [DH - Tai lieu API HIS-LIS - Token - 10-03-2023.pdf](https://github.com/dh-hos/dhg.hospitallaboratory/files/10938147/DH.-.Tai.lieu.API.HIS-LIS.-.Token.-.10-03-2023.pdf) cho TPH để bên đó cập nhật thêm chức năng lấy mẫu truyền mã XN.
