### ISSUE TITLE
Yêu cầu - Cập nhật API kết liên kết Lapconn

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitallaboratory#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN QUẬN 12**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bổ sung API kiểm tra chi phí bệnh nhân (phát sinh cùng chi trả phải thanh toán trước), tương tự như việc kiểm tra khi lấy mẫu tại Laboratory.

```

**Comment by vinh-dh** [comment]
Gửi tài liệu này [DH - Tai lieu API HIS-LIS - Token - 12-03-2023.pdf](https://github.com/dh-hos/dhg.hospitallaboratory/files/10950697/DH.-.Tai.lieu.API.HIS-LIS.-.Token.-.12-03-2023.pdf) cho Labconn xem và cập nhật phần mềm bên đó nhé!
