### ISSUE TITLE
Yêu cầu - Hỗ trợ theo đề nghị BV Tim Mạch - Cần Thơ

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitallaboratory#34]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch Cần Thơ**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
![z4290392586337_991faf36433cf2f164389c3207d1170f](https://user-images.githubusercontent.com/91751241/233900333-dcbe3bd0-ae62-49e9-9235-41748b76df83.jpg)


```

**Comment by vinh-dh** [comment]
![image](https://user-images.githubusercontent.com/112069710/233952169-75b3b91c-801b-4f25-958f-128682640b43.png)
