### ISSUE TITLE
Yêu cầu - Cập nhật API kết liên kết Lapconn

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitallaboratory#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN CHUYÊN KHOA SẢN - NHI**

**Comment by lqbinh1987** [comment]
Nhờ a @vinh-dh  build bản mới dùm em, và xây dụng server API cho BV giúp e.

**Comment by vinh-dh** [comment]
Chờ a bổ sung rồi cho hay nhe. Hiện tại anh đang vướng nhiều y/c **gấp**

**Comment by vinh-dh** [comment]
Xong nhé!

Thông tin kết nối:
- Server: `172.28.10.2:8080`
- Tài khoản: `labconn`
- Mật khẩu: `labconn`
