### ISSUE TITLE
Lỗi - Không in được kết quả XN Vi sinh, ô kết quả quá hẹp in bị thiếu chữ

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitallaboratory#36]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77000-001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Phúc Gia Khang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phucgiakhang_labo`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/uicAPWjyX)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000590` - _**MaKB**_: `2305000322` - _**MaBA**_: `MaBA` _**NgayKCB**_: `23/05/2023` - _**MaPhong**_: `KB6` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cấu hình tham số xn.sudungmauchuan = 6 (Tất cả XN trên 1 phiếu (A4 - in ngang, phần kết quả bên phải có trị số bình thường))
1- Không in được CLS Vi sinh lên phiếu kết quả
2- Cột Kết quả trên phiếu in kết quả bị thiếu chữ (kết quả Hóa sinh máu) -> Tăng động rộng ô kết quả phần hóa sinh máu
3- Khi trả kết quả cho nhiều CLS có tên dài thì bị đẩy 1 vài dòng bị đẩy qua trang thứ 2 mà không thêm vào phần kết quả bên phải.
4- Tên CLS Hóa sinh nước tiểu, Miễn dịch, Xét nghiệm khác bị ghép chung với chỉ số bình thường

![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272332/c230a4cf-37a3-4f48-b58c-9cc017b029b9)

**Comment by vinh-dh** [comment]
- [HospitalLaboratorySetup20230525](https://gofile.me/78TQg/mXllVgbgE)

**Comment by chauthanhtra** [comment]
Alo anh @vinh-dh 
Khi lưu kết quả nó không hiện form kết quả lên để in mà thoát ra ngoài danh sách
Anh chỉnh lại cho khi lưu kết quả XN xong nó hiện phiếu kết quả lên để in đi anh, khỏi phải tìm bệnh nhân vào xét nghiệm lại để mở lên in phiếu

![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272332/1b33bd15-8106-4ac7-b907-3658a32a083e)
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272332/2a6bb1af-d284-492a-985d-68fcb3807957)

**Comment by vinh-dh** [comment]
Tham số để vầy sao mà nó hiển thị lên được.

![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/112069710/cc2a657d-0002-4c00-9db6-021d924d4cbd)

**Comment by chauthanhtra** [comment]
Ok anh. Thanks anh @vinh-dh 
em không nhớ có tham số này luôn
