### ISSUE TITLE
Yêu cầu - Phiếu xét nghiệm lấy tên Buồng bệnh

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Sadec**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `sadec_cls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Phiếu xét nghiệm lấy tên buồng bệnh, hiện tại lấy theo mã buồng bệnh (mã phòng)

```
Phiếu kết quả xét nghiệm
![image](https://user-images.githubusercontent.com/96155021/190367627-4ff1f131-900e-4664-9c2b-04b0c2ee39d8.png)

**Comment by vinh-dh** [comment]
Vấn đề này em bàn với @nghivanbi thống nhất toàn hệ thống nhe. Hiện tại các phân hệ khác (phiếu chỉ định) vẫn lấy mã phòng tại ô này.

Prescription:
![image](https://user-images.githubusercontent.com/112069710/190531809-8185fd1e-f21f-44fc-8393-e11ce0bd59c2.png)

Treatment:
![image](https://user-images.githubusercontent.com/112069710/190531841-f04b56e7-4bc0-44a6-91c5-bb94efab2d41.png)

Chứ không riêng các phiếu kết quả.

**Comment by le-an-87** [comment]
Đã thống nhất không điều chỉnh!
