### ISSUE TITLE
Yêu cầu - Cài đặt lại server API kết nối LIS.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#41]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Sản Nhi ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Nhờ a Vinh cài lại server API kết nối với Labonn của BV Sản Nhi ST dùm em, vì hôm rài bị lỗi liên tục.
Do hổm rài máy server API cài trên server ảo, mà chưa tìm ra nguyên nhân lỗi, nên giờ chuyển sang cài trên server thật.
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/399da651-4c7f-4189-901f-86b714a77029)

**Comment by ongtrieuhau** [comment]
@vinh-dh thực hiện giúp em nhé

**Comment by vinh-dh** [comment]
- Server: `172.28.10.3:8080`
- Username: `labconn`
- Password: `labconn`
