### ISSUE TITLE
Lỗi - Không hiện DS bệnh nhân ngày trước chưa thực hiện

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#43]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bvhhtmct_082023_222`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi chọn danh sách BN nhưng ngày trước thì không load được danh sách những bệnh nhân có xn chưa thực hiện, mặc dù nhưng ngày trước còn nhiều XN chưa thực hiện. ví dụ như tên BN như Hình 1 còn XN chưa làm, nếu đăng nhập đúng ngày thì thấy tên, còn nếu đăng nhập ngày hiện tại và chọn 30 ngày trước thì ko load được BN nào hết

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/140be361-3ebf-4d84-83b1-2feebffb83da)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/c6dbe6b6-894f-4ca1-95cd-eb1266ae9fda)

**Comment by vinh-dh** [comment]
Để anh kiểm tra.

**Comment by lqbinh1987** [comment]
Tranh thủ này dùm em nhe anh @vinh-dh .

**Comment by vinh-dh** [comment]
Anh đang coi

**Comment by vinh-dh** [comment]
- [HospitalLaboratorySetup20230810](https://gofile.me/78TQg/UrV4ysvo2)
