### ISSUE TITLE
Lỗi - Sổ Xét nghiệm và Sổ xét nghiệm 14/BV-01 không thống kê CLS chidinhcls.bhyt = 0

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitallaboratory#44]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/8/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_labo_soxn_082023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/KLkLtgxQ0)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `08` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `HC01` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Module: Laboratory, Reports 
- Sổ xét nghiệm và sổ xét nghiệm 14/BV-01 không thống kê CLS không thanh BHYT dữ liệu chidinhcls.bhyt = 0
- Mã CLS test trên hình: HC01 

![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272332/8d52b4af-0e18-425d-87cb-46394fc64962)

![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272332/4d5fdc32-d5ec-49ff-936c-f9ac75f82e47)

**Comment by vinh-dh** [comment]
Đây không phải lỗi nhe @chauthanhtra. Do bệnh viện sử dụng tham số này:
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/112069710/6fa0108a-6014-4a6a-8c96-c341f13f5cd7)

**Comment by chauthanhtra** [comment]
Phần đối tượng em đang để mặc định là tất cả nha anh. không có chọn đối tượng BH hay trẻ em
