### ISSUE TITLE
Lỗi - Form trả kết quả xét nghiệm bị double chẩn đoán

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#45]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_labor_double_chandoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6c9BU5vwV)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022031485` - _**MaKB**_: `2310005552` - _**MaBA**_: `018596` _**NgayKCB**_: `12/10/2023` - _**MaPhong**_: `NO6` - _**MaDV**_: `23` - _**ThangKT**_: `10` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Form trả kết quả xét nghiệm bị double chẩn đoán của bệnh nhân.
test thử kết quả in ra thì không bị double nhưng trên form thì hiển thị double chẩn đoán
```
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/63c5a7e3-caea-4633-9523-710be01b1fd0)

Kết quả khi in
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/fcdff175-e228-4731-8751-4a39ed06b751)

**Comment by vinh-dh** [comment]
File: [HospitalLaboratorySetup20231013.zip](https://gofile.me/78TQg/0ULX7aOMp)

**Comment by le-an-87** [comment]
đã fix!
