### ISSUE TITLE
Lỗi - Bệnh nhân có chỉ định xét nghiệm nhưng Laboratory vào Xét nghiệm không thấy tên bệnh nhân

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#49]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77156`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Phòng Khám Đa Khoa Phúc Gia Khang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphucgiakhang_xetnghiem`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023004379` - _**MaKB**_: `2312000858` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/12/2023` - _**MaPhong**_: `CLS` - _**MaDV**_: `02.03` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Bệnh nhân có chỉ định xét nghiệm như hình dưới nhưng Laboratory 2023.12.01 vào xét nghiệm không thấy tên bệnh nhân
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/aa364ce6-c552-4add-888d-fa093872d4bb)

Laboratory mới trên admin không thấy tên bệnh nhân để trả kết quả
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/76b5be2c-46f2-44ff-a78e-930f90ac48cb)

Em cài Laboratory bản  cũ ngày 16.05.2023 thì thấy tên bệnh nhân bình thường 

![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/d053962f-19c8-4c71-83cf-406fd06c06d5)

**Comment by vinh-dh** [comment]
Nguyên nhân là do đây nè @hvtuan1987: [Yêu cầu - Ẩn đi những CLS KHÔNG THỰC HIỆN trên LABO #40](https://github.com/dh-hos/To_Lap_Trinh/issues/40)

**Comment by hvtuan1987** [comment]
Dạ ok rồi á !
