### ISSUE TITLE
Yêu cầu -  Đổ thêm thông tin ngày sinh cho LIS

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitallaboratory#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả bệnh viện kết nối TPH**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) ``
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`]()

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
![image](https://user-images.githubusercontent.com/91751241/190598718-b3b27fae-0399-4f89-b2d1-a2219645c750.png)

Bổ sung truyền cột ngaysinh (date), trong trường hợp bệnh nhân chỉ có năm sinh thì truyền ngaysinh = null.
```

**Comment by vinh-dh** [comment]
Ngày sinh kiểu chuỗi đi, thêm nữa là chỉ có ngày sinh thì cứ để năm sinh.

**Comment by nghivanbi** [comment]
Thống nhất  truyền cột ngaysinh (varchar: dd/MM/yyyy), trong trường hợp bệnh nhân chỉ có năm sinh thì truyền ngaysinh = "" nha.

**Comment by vinh-dh** [comment]
Bổ sung cột **_ngaysinh_**, Định dạng _DD/MM_. Chi tiết tài liệu mô tả: [DH - Tai lieu API HIS-LIS - Token - 20-09-2022.pdf](https://github.com/dh-hos/dhg.hospitallaboratory/files/9605446/DH.-.Tai.lieu.API.HIS-LIS.-.Token.-.20-09-2022.pdf)

Cập nhật DLL API: [DH.LIS.dll](https://github.com/dh-hos/dhg.hospitallaboratory/files/9605455/DH.LIS.zip)

**Comment by nghivanbi** [comment]
Gởi lại TPH để kết hợp nha Vinh.
