### ISSUE TITLE
Lỗi - Lỗi kết nối LIS - Chưa được cấp phép kết nối từ D

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#50]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hồng Dân**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
BV đang bị lỗi, hệ thống LIS kết nối HIS không đc, báo lỗi như hình dưới. Hỗ trợ gấp dùm em.

![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/d311a7c6-2919-44e2-9111-05cb23590a40)
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/37959d28-d841-4d2f-bc15-0a64c05759d2)
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/6a5302fe-2b5c-4608-8c39-c7bb8969523f)
Pass anydesk: **@TPH#lis@015**

**Comment by vinh-dh** [comment]
Lấy data đem về anh debug code nhé!

**Comment by vinh-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/112069710/f1537e6c-8e6f-43a7-88a8-59d0634d0a62)

Thử tại máy anh thì ok. Nhờ BV đổi máy khác cài thử xem sao nhé @lqbinh1987

**Comment by lqbinh1987** [comment]
Dạ

> ![image](https://private-user-images.githubusercontent.com/112069710/307716648-f1537e6c-8e6f-43a7-88a8-59d0634d0a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzY3MjcsIm5iZiI6MTcwODkzNjQyNywicGF0aCI6Ii8xMTIwNjk3MTAvMzA3NzE2NjQ4LWYxNTM3ZTZjLThlNmYtNDNhNy04OGE4LTU5ZDA2MzRkMGE2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwODMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2VlNDNkMTZmOGJlNWE1YzMyYTA2YzJmZTMwNDM1OTg5OWExODIyODEwNGI4OGMxYzM3NDJlZGEzMjlkMzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wC01oyB_Ew1eWZ2dRUZ3WcotEHao82DdQH7gqDLt7qI)
> 
> Thử tại máy anh thì ok. Nhờ BV đổi máy khác cài thử xem sao nhé @lqbinh1987

**Comment by vinh-dh** [comment]
Khắc phục được lỗi này rồi nhe @lqbinh1987. Nguyên nhân là do máy chủ API cấu hình sai DNS. Cách khắc phục, đổi lại DNS Google là được:
```
8.8.8.8
8.8.4.4
```

**Comment by vinh-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/112069710/bc9240cd-3779-4a4f-b06b-fdffe518118a)

**Comment by lqbinh1987** [comment]
Dạ ok rồi nhe anh.
