### ISSUE TITLE
Lỗi - Sổ xét nghiệm báo cáo quí năm không load được bệnh nhân đã thực hiện xét nghiệm (BV YHCT CT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#51]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_ct_soxn_29022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_yhct_ct_soxn_29022024`](https://gofile.me/78TQg/Jp6tP757C)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023025621` - _**MaKB**_: `2312001308` - _**MaBA**_: `2023004819` _**NgayKCB**_: `13/12/2023` - _**MaPhong**_: `C14` - _**MaDV**_: `03` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `TO04` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân đã trả kết quả xét nghiệm khi xuất báo cáo sổ xét nghiệm tại module Labor và Reports.
- xuất theo tháng có dữ liệu bệnh nhân.

==> xuất báo cáo sổ xét nghiệm theo quí 4 và năm không lấy được thông tin bệnh nhân.

```
Sổ xét nghiệm
+ xuất tháng
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/212de4e6-9728-4921-889c-d2e660242884)

- xuất quí 4/2023 và năm không có bệnh nhân
+ Labor:
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/a652dd8a-6fd6-453e-aec8-9abe73f7403e)
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/4794a29e-edfd-4b0e-a9fc-953c7cc3014b)

+ Reports:
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/b250757c-77a3-414d-bc33-0603a8c26118)
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/0d441758-5afc-4ca2-9dd6-ec3012502a49)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240301.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240301zip---01032024)
- File: [HospitalLaboratorySetup20240301.zip](https://gofile.me/78TQg/B0ya25kSe) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitallaboratory/blob/main/CHANGELOG.md#file-hospitallaboratorysetup20240301zip---01032024)

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/f594ddd6-6a2e-4d8c-8155-47137070c95a)
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/d2b17d32-f6fe-4b63-baf7-0cd49484efe2)
