### ISSUE TITLE
Lỗi - Xét nghiệm Đờm Lưu kết qua xong đóng form và vào xem lại kết quả lỗi

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa Sa Đéc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_tpsadec_032024022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023054352` - _**MaKB**_: `2402024882` - _**MaBA**_: `2024007604` _**NgayKCB**_: `04/03/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `NHIEM` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `AF02` - _**PhieuYC**_: `PhieuYC`

Xét nghiệm đờm Sau khi trả kết quả lưu lại và xem kết quả bình thường nhưng đóng Form Xét nghiệm đờm vào xem lại bệnh nhân vừa trả kết quả báo lỗi như hình dưới (Tất cả các bệnh nhân có trả kết quả Xét nghiệm mã cls AF02 đều bị như nhau)
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/546b2b15-5708-48fb-8a9b-0af15e772519)

Chi tiết lỗi:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Npgsql.NpgsqlException:
syntax error at or near "macls"
Severity: ERROR
Code: 42601
   at DH.DALCLS.DataAdapter.DOMAdapter.GetNgayTH(String mabn, String makb, DateTime ngaykcb, String macls)
   at DH.BLLCLS.DOM.GetNgayTH(String mabn, String makb, DateTime ngaykcb, String macls)
   at Utilities.Forms.Subclinical.Laboratory.FrmDOM.FrmDOM_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DH.Laboratory
    Assembly Version: 3.24.301.0
    Win32 Version: 3.24.0301.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/DH.Laboratory.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------

Hoặc đăng nhập ngày hiện tại và Vào Tab Xét nghiệm đòm và chọn 10 ngày trước như hình dưới và bấm nút thực hiện vẫn báo lỗi tương tự như trên

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra.

**Comment by vinh-dh** [comment]
- File: [HospitalLaboratorySetup20240312.zip](https://gofile.me/78TQg/B0ya25kSe) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitallaboratory/blob/main/CHANGELOG.md#file-hospitallaboratorysetup20240312zip---12032024)

**Comment by hvtuan1987** [comment]
ok rồi á !
