### ISSUE TITLE
Lỗi - hủy kết quả tế bào tử cung (BV Phụ sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#53]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_dn_loaibenhpham`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/35CIe9uXG)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân%20test-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2403000001` - _**NgayKCB**_: `11/03/2024` - _**MaPhong**_: `10` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `KY08` - _**PhieuYC**_: `Hủy kết quả tế bào tử cung`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lỗi hủy kết quả tế bào tử cung.
Bệnh nhân dùng tài khoản admin để trả kết quả tế bào từ cung mã KY08.
-> khi dùng tài khoản admin để hủy kết quả thì báo không đúng tài khoản => không hủy kết quả được.
* chỉnh kết quả thì phần mềm chấp nhận

```
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/ede55dd4-5e09-4046-9535-53a17f50c13b)
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/b5e6d63a-e83a-4725-8c19-5ea89f628a1d)

**Comment by vinh-dh** [comment]
- File: [HospitalLaboratorySetup20240313.zip](https://gofile.me/78TQg/B0ya25kSe) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitallaboratory/blob/main/CHANGELOG.md#file-hospitallaboratorysetup20240313zip---13032024)
