### ISSUE TITLE
Lỗi - Không nhận KQ từ LIS.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#54]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TP Sa Đéc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_tpsadec_loi_lis`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024008268` - _**MaKB**_: `MaKB` - _**MaBA**_: `2024009191` _**NgayKCB**_: `12/03/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `NTH` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Theo như hình thì BN có chỉ định hàng loạt các XN, nhưng khi nhận KQ từ TPH thì chỉ nhận được một số CLS, còn lại 1 số CLS không nhận được kết quả(Hình 1), bên TPH thì báo lỗi:
"code":100,"message":"Không kết nối được máy chủ API. Chi tiết: String was not recognized as a valid DateTime. 

Khi e chạy thử postman trả KQ tại BV thì báo lỗi(Hình 2).

**Hình 1:**
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/346d43e2-ff65-4d06-a484-22154857ddda)

**Hình 2:**
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/86df0b1e-a4bf-45f7-ad14-5c81292741e7)

**Comment by gh-dh-bot-02** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại📣

**Comment by gh-dh-bot-02** [comment]
<details> <summary>   ℹ️<code>2024-19-03 08:28:21</code> <code>@lqbinh1987</code><code>projects_v2_item.created</code> <code>[Giám đốc theo dõi (All Issues).#2].[]:::[] => []</code> </summary> <code>[bot]</code><code>1.24.0319.0800@az-o-adv-more-alien-weekly-ubuntu-latest-definitionId28-1710810279489</code><code>[<a href='https://dev.azure.com/o-adv/more-alien-weekly-ubuntu-latest/_build/results?buildId=4177&view=logs'>webhook-logs</a>]</code> </br></br> <code>[info.0]</code><code>"[Giám đốc theo dõi (All Issues).#2].[]:::[] => []"</code> </br></br> <code>[info.1]</code><code>{"projectId":"PVT_kwDOBk3i3s4ACYUf","itemId":"PVTI_lADOBk3i3s4ACYUfzgNj4Pk","fieldId":"","textValue":"","optionIdValue":"","field_node_id":"","field_type":"","project":{"title":"Giám đốc theo dõi (All Issues)","number":"2"},"oldValue":{"PVTF_lADOBk3i3s4ACYUfzgBYCGk":{"field":{"createdAt":"2022-06-04T09:35:44Z","dataType":"LABELS","databaseId":5769321,"id":"PVTF_lADOBk3i3s4ACYUfzgBYCGk","name":"Labels","updatedAt":"2022-08-22T01:22:02Z"},"fieldName":"Labels"}},"batchMutations":[],"isOnlyBatchMutations":false,"revertChanges":{}}</code></details>

**Comment by gh-dh-bot-02** [comment]
<details> <summary>   ℹ️<code>2024-19-03 08:28:21</code> <code>@lqbinh1987</code><code>projects_v2_item.created</code> <code>[Giám đốc theo dõi (All Issues).#2].[]:::[] => []</code> </summary> <code>[bot]</code><code>1.24.0319.0800@az-o-adv-more-alien-weekly-ubuntu-latest-definitionId28-1710810279489</code><code>[<a href='https://dev.azure.com/o-adv/more-alien-weekly-ubuntu-latest/_build/results?buildId=4177&view=logs'>webhook-logs</a>]</code> </br></br> <code>[info.0]</code><code>"[Giám đốc theo dõi (All Issues).#2].[]:::[] => []"</code> </br></br> <code>[info.1]</code><code>{"projectId":"PVT_kwDOBk3i3s4ACYUf","itemId":"PVTI_lADOBk3i3s4ACYUfzgNj4Pk","fieldId":"","textValue":"","optionIdValue":"","field_node_id":"","field_type":"","project":{"title":"Giám đốc theo dõi (All Issues)","number":"2"},"oldValue":{"PVTF_lADOBk3i3s4ACYUfzgBYCGk":{"field":{"createdAt":"2022-06-04T09:35:44Z","dataType":"LABELS","databaseId":5769321,"id":"PVTF_lADOBk3i3s4ACYUfzgBYCGk","name":"Labels","updatedAt":"2022-08-22T01:22:02Z"},"fieldName":"Labels"}},"batchMutations":[],"isOnlyBatchMutations":false,"revertChanges":{}}</code></details>

**Comment by vinh-dh** [comment]
Gửi luôn chuỗi text json để a test nhe @lqbinh1987.

**Comment by lqbinh1987** [comment]
> Gửi luôn chuỗi text json để a test nhe @lqbinh1987.

{
  "mabn": "2024008268",
  "maloai": "SH",
  "manv_chidinh": "722",
  "manv_thuchien": "634",
  "thangkt": "03",
  "namkt": "2024",
  "sophieuyeucau": "2403011704",
  "madichvu": "DI500",
  "ngaychidinh": "2024-03-12T10:30:00",
  "ketqua": "5.04",
  "trisobinhthuong": "3.9 - 6.4",
  "batthuong": 0,
  "dvt": "mmol/L",
  "mamay": null,
  "ngaykq": "2024-03-12T14:51:12"
}

**Comment by vinh-dh** [comment]
Anh test thử tại máy anh thì không lỗi gì hết:
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/112069710/f76c84db-aa06-4314-b7d2-a92c9d399aaf)
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/112069710/aa5025bf-c86d-4a9c-bd10-db18c1e4f5ea)

Anh mới build lại DLL mới. Em lấy update cho BV rồi thử lại xem sao: [DH.LIS.dll](https://github.com/dh-hos/oLibraries/commit/512677fc451616ec302b4e63242def04468547af)

**Comment by lqbinh1987** [comment]
Đã hỗ trợ
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/99630883/1e061e68-0ddf-451b-9b36-efaa5564ffd9)
