### ISSUE TITLE
Lỗi - Sinh thiết khi xem lại 10 ngày trước đó không load lại được cận lâm sàng đã chỉ định

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#55]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa Sa Đéc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_tpsadec_032024022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010644` - _**MaKB**_: `2403003465` - _**MaBA**_: `2024008137` _**NgayKCB**_: `04/03/2024` - _**MaPhong**_: `PTGMHS_PM` - _**MaDV**_: `PTGMHS` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `XE27` - _**PhieuYC**_: `PhieuYC`

Xét nghiệm Sinh thiết có chỉ định cận lâm sàng trước trước đó nhưng đăng nhập ngày hiện tại và xem lại 10 ngày trước không load được cận lâm sàng đã chỉ định như hình dưới. Khi bấm hộp thoại đồng ý và xuất hiện lỗi
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/1967be90-e3d0-4698-aaa2-81f021264992)

Chi tiết lỗi
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Janus.Windows.GridEX.GridEX.set_Row(Int32 value)
   at Utilities.Forms.Subclinical.Laboratory.FrmDanhSachST.btn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at Janus.Windows.EditControls.UIButton.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DH.Laboratory
    Assembly Version: 3.24.322.0
    Win32 Version: 3.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/DH.Laboratory.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Statistics
    Assembly Version: 1.24.322.0
    Win32 Version: 1.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Statistics.DLL
----------------------------------------
DataHelper
    Assembly Version: 1.24.322.0
    Win32 Version: 1.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/DataHelper.DLL
----------------------------------------
Npgsql
    Assembly Version: 2.2.3.0
    Win32 Version: 2.2.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Npgsql.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
DH.BLLCLS
    Assembly Version: 3.24.322.0
    Win32 Version: 3.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/DH.BLLCLS.DLL
----------------------------------------
DH.PublicCLS
    Assembly Version: 3.24.322.0
    Win32 Version: 3.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/DH.PublicCLS.DLL
----------------------------------------
LibraryApp
    Assembly Version: 4.23.1127.1
    Win32 Version: 4.23.1127.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/LibraryApp.DLL
----------------------------------------
Utilities
    Assembly Version: 1.24.322.0
    Win32 Version: 1.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Utilities.DLL
----------------------------------------
Janus.Windows.ExplorerBar.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Janus.Windows.ExplorerBar.v3.DLL
----------------------------------------
Janus.Windows.Common.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Janus.Windows.Common.v3.DLL
----------------------------------------
MessageBoxAdv
    Assembly Version: 4.22.615.3
    Win32 Version: 4.22.0615.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/MessageBoxAdv.DLL
----------------------------------------
DH.DALCLS
    Assembly Version: 3.24.322.0
    Win32 Version: 3.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/DH.DALCLS.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Mono.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Mono.Security.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OTH.Common
    Assembly Version: 1.24.117.0
    Win32 Version: 1.24.0117.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/OTH.Common.DLL
----------------------------------------
OTH.Adapter
    Assembly Version: 1.24.202.2
    Win32 Version: 1.24.0202.2
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/OTH.Adapter.DLL
----------------------------------------
OTH.Entity
    Assembly Version: 1.24.129.2
    Win32 Version: 1.24.0129.2
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/OTH.Entity.DLL
----------------------------------------
OTH.SQL
    Assembly Version: 1.22.615.4
    Win32 Version: 1.22.0615.4
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/OTH.SQL.DLL
----------------------------------------
OTH
    Assembly Version: 1.24.117.1
    Win32 Version: 1.24.0117.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/OTH.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Janus.Windows.CalendarCombo.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Janus.Windows.CalendarCombo.v3.DLL
----------------------------------------
Janus.Windows.UI.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Janus.Windows.UI.v3.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
License
    Assembly Version: 3.24.202.1
    Win32 Version: 3.24.0202.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/License.DLL
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
Role
    Assembly Version: 1.23.1006.0
    Win32 Version: 1.23.1006.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Role.DLL
----------------------------------------
Janus.Windows.GridEX.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Janus.Windows.GridEX.v3.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
OTH.ChilkatRR
    Assembly Version: 1.22.615.3
    Win32 Version: 1.22.0615.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/OTH.ChilkatRR.DLL
----------------------------------------
ChilkatDotNet4
    Assembly Version: 9.5.0.73
    Win32 Version: 9.5.0.73
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/ChilkatDotNet4.DLL
----------------------------------------
Janus.Data.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Janus.Data.v3.DLL
----------------------------------------
Ctrl
    Assembly Version: 3.22.615.5
    Win32 Version: 3.22.0615.5
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/Ctrl.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
DH.ReportCLS
    Assembly Version: 3.24.322.0
    Win32 Version: 3.24.0322.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Laboratory/DH.ReportCLS.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by vinh-dh** [comment]
Ok, để a kiểm tra.

**Comment by vinh-dh** [comment]
- File: [HospitalLaboratorySetup20240405.zip](https://gofile.me/78TQg/B0ya25kSe) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitallaboratory/blob/main/CHANGELOG.md#file-hospitallaboratorysetup20240405zip---05042024)

**Comment by hvtuan1987** [comment]
Dạ ok rồi á anh !
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/694669a7-955a-4ccc-88b4-ac3e651fcdc9)
