### ISSUE TITLE
Lỗi - Mục Cấu hình các mẫu trả kết quả không hiển thị 2 tab: Xét nghiệm và Xét nghiệm TT37

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitallaboratory#56]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92085`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Thần Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tamthan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/FcYY8AAhi

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
  

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Mục Cấu hình mẫu trả kết quả không hiển thị 2 tab: Xét nghiệm và Xét nghiệm TT37
 + Cấu hình Huyết học
 + Cấu hình hóa sinh NT
 + Cấu hình hóa sinh máu
 + Cấu hình rối loạn đông cầm máu
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/3e15cb08-818c-4025-ba4c-2f4845ef75de)

DM CLS thì đang sử dụng theo TT37
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/d2e126ed-ce1b-4bbe-95d5-48a0e40bb30f)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitallaboratory/56)
<details> <summary>   ℹ️<code>2024-05-04 14:50:25</code> <code>@minhduc2it</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NuhEBnx82qR_NPn4I3B'>-NuhEBnx82qR_NPn4I3B</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1712300814197</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8566300854'>webhook-logs</a>]</code></details>
