### ISSUE TITLE
Lỗi - Cấu hình XN phiếu chuẩn: Khi chọn XN để cấu hình không thể hiện XN được chọn

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitallaboratory#57]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92085`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Thần Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tamthan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/FcYY8AAhi

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi sử dụng tham số xn.sudungmauchuan = 4 
Cấu hình XN phiếu chuẩn: Khi chọn XN để cấu hình không thể hiện XN được chọn

![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/ad2d8b45-dc3f-45ba-954d-60fe9f337975)

Khi chọn xong không hiển thị mã CLS được chọn
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/d7a79eff-d4f5-4c91-baaf-6c09b31de226)

Video thao tác 

https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/6d8c5177-11ec-40cc-b022-b6ac4a6cb9d0

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitallaboratory/57)
<details> <summary>   ℹ️<code>2024-08-04 15:31:46</code> <code>@minhduc2it</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NuwpQdHZtKcShUM0Ys2'>-NuwpQdHZtKcShUM0Ys2</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1712563781068</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8596697868'>webhook-logs</a>]</code></details>

**Comment by vinh-dh** [comment]
Để anh kiểm tra.

**Comment by vinh-dh** [comment]
- File: [HospitalLaboratorySetup20240411.zip](https://gofile.me/78TQg/B0ya25kSe)

**Comment by minhduc2it** [comment]
Đã fix.
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/14cf17a1-2685-431c-8545-66326917ec0a)

Kiểm tra nhận bệnh khám bệnh, xuất dữ liệu XML bình thường.
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/0b345d5a-a582-4753-b1d1-bd630f5cac12)
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/98437757/3c664df7-20e7-4a26-bcf4-9bb6753334fb)
