### ISSUE TITLE
Lỗi - Kết quả kiểu chuổi, Chỉ số bình thường và kết quả mặc định cùng chuổi nhưng In phiếu kết quả lại in đậm

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitallaboratory#58]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK Medic Sài Gòn 2**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_sagomed2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020004599` - _**MaKB**_: `2405000325` - _**MaBA**_: `MaBA` _**NgayKCB**_: `04/05/2024` - _**MaPhong**_: `ĐY2` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DE10` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cận lâm sàng mã DE10 có cấu hình chỉ số bình thường ÂM TÍNH và Kết quả Mặc định ÂM TÍNH như hình dưới
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/be53bb00-75ea-49a8-b45f-cd345fef46b4)

Form trả kết quả như hình dưới
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/00aff293-9f81-4c4a-b53b-fb7a7109700d)

![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/fd9f3ca2-6586-4440-88bb-fd998322c29d)

Phiếu Kết quả lại IN Đậm như hình dưới
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/68ee43d0-d779-446e-bf72-e18974f32dcc)
Phòng khám nhờ chỉnh lại nếu cùng chuổi kết quả thì không in đậm

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitallaboratory/58)

**Comment by vinh-dh** [comment]
- File: [HospitalLaboratorySetup20240504.zip](https://gofile.me/78TQg/B0ya25kSe) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitallaboratory/blob/main/CHANGELOG.md#file-hospitallaboratorysetup20240504zip---04052024)

**Comment by hvtuan1987** [comment]
Dạ ok rồi á anh @vinh-dh 
Mà nếu là Dương tính thì người dùng phải tự check vô bất thường hả anh Vinh ! Tại em để Dương tính mà phần mềm hong tự check á !

**Comment by vinh-dh** [comment]
Kết quả kiểu số và phải có định nghĩa min/max thì phần mềm mới bắt được bất thường. Các trường hợp còn lại không có căn cứ để tự động, người dùng tự xác định.

**Comment by hvtuan1987** [comment]
Dạ !
