### ISSUE TITLE
Lỗi - Báo cáo lượt chỉ định cls không load được cls sinh thiết (BV Phụ Sản CT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#59]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_bcchidinhcls_09052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_bcchidinhcls_09052024`](https://gofile.me/78TQg/WeBEzwU1j)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024022369` - _**MaKB**_: `2405006508` - _**NgayKCB**_: `09/05/2024` - _**MaPhong**_: `20` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `VI11`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Các báo cáo lượt chỉ định cls không load được cls sinh thiết mã cls VI11:
1. Lượt chỉ định theo khoa
2. Lượt chỉ định theo phòng
3. lượt chỉ định theo bác sĩ
4. lượt chỉ định theo xét nghiệm

```
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/42438ab2-4a7e-48cc-bbf2-68f148d136cd)
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/dcb5d07a-7e80-41b9-b63d-41d9b1cc13a6)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitallaboratory/59)
<details> <summary>   ℹ️<code>2024-09-05 16:23:06</code> <code>@le-an-87</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NxReT0l-3ahpQl5f_g1'>-NxReT0l-3ahpQl5f_g1</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1715245706349</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/9015010228'>webhook-logs</a>]</code></details>

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/2486290e-2372-4819-8503-6d29e9cb3b66)
