### ISSUE TITLE
Lỗi - Phiếu kết quả in sai ngày thực hiện (BV Ung Bướu)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_xn_ngakt_09072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_ungbuou_xn_ngakt_09072024`](https://gofile.me/78TQg/h6IwPcpau)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023012166` - _**MaKB**_: `2407001857` - _**MaBA**_: `013324` _**NgayKCB**_: `03/07/2024` - _**MaPhong**_: `NO3` - _**MaDV**_: `23` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI25` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xét nghiệm khi trả kết quả xong in giờ thực hiện không đúng

* trường hợp chỉ định 1 lượt nhiều cls và chọn từng cls trả kết quả theo từng giờ khác nhau.
-> Labor in giờ thực hiện cùng giờ với lần đầu thực hiện.
Như cls DI25 thực hiện lúc 10:20 khi in kết quả hiển thị 09:21

```
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/bfda32bc-3d09-4f98-a7f3-33b763ac3121)
![ảnh](https://github.com/dh-hos/dhg.hospitallaboratory/assets/96155021/5355f14e-e914-49ce-869c-c0eb768d30f3)

**Comment by vinh-dh** [comment]
Để anh kiểm tra.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 DH.Laboratory.exe v.3.24.0710.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32407100-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32407100-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32407100-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi phiếu kết quả xét nghiệm in sai ngày thực hiện.

- ☑: https://github.com/dh-hos/dhg.hospitallaboratory/issues/61

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Laboratory.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/user-attachments/assets/3eb4d405-911f-499c-a4a3-bb21c6af8471)
![ảnh](https://github.com/user-attachments/assets/911b375f-a410-4d59-a0fd-793cbe75796d)
