### ISSUE TITLE
Lỗi - Kết nối API chưa bắt được theo tham số và truyền sai dữ liệu.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitallaboratory#62]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_pknamphuong29`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/kn5HkBWUF)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1.  Đối với BN BHYT có làm dịch vụ BHYT không thanh hoặc chênh lệch hoặc %CTT nhưng khi sử dụng hàm SP_CheckChiPhi_Lay_Mau để check chi phí thì lại vằng ra lỗi Code 1 như hình dưới, mặc dù tham số **bhytthuchenhlech=0 là không bắt buộc đóng tiền**

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024066942` - _**MaKB**_: `2408027983` - _**MaBA**_: `MaBA` _**12/09/2024**_: `NgayKCB` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
![image](https://github.com/user-attachments/assets/10e5f62e-187a-4def-b884-62832d5e5bd2)

2. Đối với trường hợp BN Khám sức khỏa hợp đồng, khi sử dụng hàm **SP_LIS_Order** để lấy thông tin chỉ định thì địa chỉ lấy sai thông tin, địa chỉ lại lấy tên công ty của BN công tác.

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024066952` - _**MaKB**_: `2408028016` - _**MaBA**_: `MaBA` _**12/09/2024**_: `NgayKCB` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
![image](https://github.com/user-attachments/assets/5d0a0187-50ac-4fd6-9ac7-9deb7f79e9d5)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Để anh kiểm tra.

**Comment by vinh-dh** [comment]
Nè @lqbinh1987: `macls = HB13` , BHYT không thanh, chưa thu nữa. Thì phát sinh chi phí là đúng, đâu có sai.
![image](https://github.com/user-attachments/assets/4ace8e1f-5831-4616-8cfb-044d4515ae71)

**Comment by vinh-dh** [comment]
Còn về địa chỉ thì quy tắc lấy trước giờ là ưu tiên nơi công tác rồi mới tới địa chỉ người bệnh. Không có bắt riêng theo đối tượng. Đây không phải lỗi.

**Comment by lqbinh1987** [comment]
> Nè @lqbinh1987: `macls = HB13` , BHYT không thanh, chưa thu nữa. Thì phát sinh chi phí là đúng, đâu có sai.
> 
> ![image](https://github.com/user-attachments/assets/4ace8e1f-5831-4616-8cfb-044d4515ae71)
> 
> 

Nhưng BN này là đối tượng BHYT mà anh, và tham số bhytthuchenhlech=0 là không bắt buộc đóng tiền á anh.

**Comment by vinh-dh** [comment]
> ![image](https://github.com/user-attachments/assets/4ace8e1f-5831-4616-8cfb-044d4515ae71)

Ca này BHYT, nhưng xét nghiệm là BHYT không thanh, nên khi đó nó được áp dụng tham số thu1lan (mà thu1lan = 1).

**Comment by lqbinh1987** [comment]
💡KIỂM TRA SẢN PHẨM💡
***
Mô tả lỗi:
Anh @vinh-dh .
Em mới test lại , nếu theo như anh nói thì như vậy sẽ không giống như Labo bắt theo diễn giải của tham số bhytthuchenhlech=0 là  _....Bệnh nhân BHYT có **thu chênh lệch/BHYT không thanh** khi thực hiện CLS....._
Vì hiện tại Labo đang bắt theo đúng tham số bhytthuchenhlech, vẫn lấy mẫu được đối với BN BHYT chỉ định **BHYT không thanh**
![image](https://github.com/user-attachments/assets/2d49c84e-888d-40f2-b279-7deedce039e9)
***
Thông tin bệnh nhân(nếu có)
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `Tên data`
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

***

**Comment by vinh-dh** [comment]
Để anh kiểm tra trường hợp này.

**Comment by vinh-dh** [comment]
@lqbinh1987: cập nhật [DH.LIS-16-09-2024.zip](https://github.com/user-attachments/files/17009499/DH.LIS-16-09-2024.zip)

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi
![image](https://github.com/user-attachments/assets/648bde34-fd1c-4ecb-8a04-d30ed9b24b29)
![image](https://github.com/user-attachments/assets/d38b5503-d514-407a-bd98-3a333b183101)
