### ISSUE TITLE
Lỗi - Không chỉnh được ngày giờ lấy mẫu khi chỉnh kết quả XN đã trả kết quả

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitallaboratory#64]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT H.Tam Nông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tamnong_chinhngaylaymaukhidaluu_formtrakq_15102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/aCtnExqrv)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022012800` - _**MaKB**_: `2410003784` - _**MaBA**_: `2024005976` _**NgayKCB**_: `14/10/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `10` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `HU1139` - _**PhieuYC**_: `PhieuYC`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân đã trả kết quả cls XN. Khi chỉnh kết quả CLS XN trên Laboratory người dùng chỉnh lại ngày giờ lấy mẫu (ngày giờ thực hiện) trên form nhưng khi lưu lại thì phần mềm không lưu được ngày giờ lấy mẫu đã chỉnh (vào xem lại kết quả thì vẫn hiện ngày giờ cũ)

![](https://i.imgur.com/07hrd47.png)
![](https://i.imgur.com/fdRf3jE.png)
![](https://i.imgur.com/j313UPi.png)

**Comment by vinh-dh** [comment]
Để anh kiểm tra lại.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 DH.Laboratory.exe v.3.24.1022.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32410220-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32410220-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32410220-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi: Không chỉnh được ngày giờ lấy mẫu khi chỉnh kết quả XN đã trả kết quả.

![image](https://github.com/user-attachments/assets/33874aed-e132-47ad-b231-c2e978c2c626)

- ☑: https://github.com/dh-hos/dhg.hospitallaboratory/issues/64

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Laboratory.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '29/10/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm DH.Laboratory.exe v.3.24.1022.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Laboratory đã fix lỗi  Không chỉnh được ngày giờ lấy mẫu khi chỉnh kết quả XN đã trả kết quả
  - Test bệnh nhân khác chưa phát hiện lỗi liên quan

- Hình ảnh: 
  - Bệnh nhân báo lỗi
![](https://i.imgur.com/xHclBUg.png)
![](https://i.imgur.com/n7izMLL.png)
![](https://i.imgur.com/4z6orby.png)

  - Bệnh nhân khác
![](https://i.imgur.com/i77nqNW.png)
![](https://i.imgur.com/JrDT3pI.png)
![](https://i.imgur.com/aawVu6x.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
