### ISSUE TITLE
Lỗi - Xem kết quả xét nghiệm hiển thị nhiều lần (BV Phụ Sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#65]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_28102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
- 
###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024088322` - _**MaKB**_: `2410019350` - _**MaBA**_: `018696` _**NgayKCB**_: `27/10/2024 6:55:00 CH` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `08` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `HB07`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng xem kết quả -> phần mềm hiển thị trang kết quả nhiều lần cùng 1 cls.
```
Trang kết quả hiển thị nhiều lần
![ảnh](https://github.com/user-attachments/assets/996e13d8-8602-4857-ab86-0ec2be8f9e18)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian dự kiến hoàn thành: 2024-11-04.

**Comment by le-an-87** [comment]
chuyển sang issu https://github.com/dh-his/Ghi_Nhan_Loi/issues/20
