### ISSUE TITLE
Lỗi - Xem (in) kết quả xét nghiệm báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitallaboratory#7]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_chauthanh_bt_kqxn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022022861` - _**MaKB**_: `2209008217` - _**MaBA**_: `002602` _**NgayKCB**_: `22/09/2022` - _**MaDV**_: `01` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xem (in) kết quả xét nghiệm báo lỗi lấy dữ liệu từ server

```
Chọn xem để in kết quả báo lỗi
![image](https://user-images.githubusercontent.com/96155021/191699941-514dda21-ac0f-42db-a507-da31c4e232de.png)
Lỗi lấy dữ liệu từ server
![image](https://user-images.githubusercontent.com/96155021/191700028-aa63ef8f-8970-483e-917c-124598cc20d5.png)

**Comment by vinh-dh** [comment]
Ca này kết quả được đổ từ phần mềm LIS của TPH. LIS TPH đổ về không có mã nhân viên thực hiện, nên Laboratory không nhận diện được đầy đủ thông tin, nên lỗi:
![image](https://user-images.githubusercontent.com/112069710/191704732-fd081cf8-e716-4b74-8ff4-fc34e4fc9941.png)

Em nhắn bệnh viện báo với LIS TPH đổ kết quả về HIS bị thiếu mã nhân viên thực hiện rồi!
