### ISSUE TITLE
Yêu cầu - Bổ xung chức năng xoá huỷ kết quả XN Tế bào tử cung

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitallaboratory#8]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả đơn vị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_moduc_092022_fees_loadsaichiphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bổ sung thêm chức năng huỷ kết quả XN Tế bào tử cung
![ảnh](https://user-images.githubusercontent.com/97272332/193222314-21dc5d83-bdd7-49ff-a8e7-28fb1c047457.png)

**Comment by vinh-dh** [comment]
Ok, để a bổ sung.

**Comment by vinh-dh** [comment]
[Laboratory 04/10/2022](https://www.fshare.vn/file/H7AIHLBH9IHO)
