### ISSUE TITLE
Yêu cầu - Quản lý định mức hóa chất theo từng máy xét nghiệm (BV Trà Cú)

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitallaboratory#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT HUYỆN TRÀ CÚ**

**Comment by vinh-dh** [comment]
@lqbinh1987 em chuẩn bị sẵn data (mới nhất) Trà Cú nhe, khi làm có cái để test.

**Comment by lqbinh1987** [comment]
Tên data nhe anh @vinh-dh: binh_tracu

**Comment by vinh-dh** [comment]
Các bước cập nhật:
- Chạy script (theo tuần tự từ 1->3)
![image](https://user-images.githubusercontent.com/112069710/197100359-008ce7b6-9d39-4c10-887b-aa70d73a6b11.png)

- [Laboratory 21/10/2022](https://www.fshare.vn/file/9MZV4OTUGFK9)

- Cập nhật [Mã máy] cho các hóa chất đã được định mức. Phần mềm có bổ sung thêm nút **[Cập nhật mã máy rỗng]** đối với các định mức cũ chưa có mã máy.
![image](https://user-images.githubusercontent.com/112069710/197100723-bd5170fb-038f-456f-a691-616ae07ce8dc.png)
